version: "2"

services:
  # Servidor MySQL que precarga el fichero current.sql
  mhedev-mysql:
    image: mysql:5.6.51
    hostname: mhedev-mysql
    container_name: mhedev-mysql
    environment:
      - SERVICE_NAME=mhedev-mysql
      - MYSQL_DATABASE=mhedev
      - MYSQL_USER=mhedev
      - MYSQL_PASSWORD=mhedev
      - MYSQL_ROOT_PASSWORD=6aEGPf%2@4saAe*4h++94
#    volumes:
#      - ./wordpress/current.sql:/docker-entrypoint-initdb.d/model.sql:ro
    expose:
      - 3306
    ports:
      - '3306:3306'

  # PhpMyAdmin disponible para operar con el servidor MySQL
  mhedev-phpmyadmin-loc:
    image: phpmyadmin/phpmyadmin:4.7
    hostname: mhedev-phpmyadmin-loc
    container_name: mhedev-phpmyadmin-loc
    environment:
      - SERVICE_NAME=mhedev-phpmyadmin-loc
      - PMA_HOST=mhedev-mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=6aEGPf%2@4saAe*4h++94
    ports:
      - '8081:80'
    depends_on:
      - mhedev-mysql

  wordpress-alpine:
    image: wordpress:php7.4-apache
    hostname: wordpress-alpine
    container_name: wordpress-alpine
    environment:
      - SERVICE_NAME=wordpress-alpine
      - WORDPRESS_DB_HOST=mhedev-mysql
      - WORDPRESS_DB_USER=mhedev
      - WORDPRESS_DB_PASSWORD=mhedev
      - WORDPRESS_DB_NAME=mhedev
    volumes:
      - ./wordpress:/var/www/html
    expose:
      - 22
    ports:
      - '8080:80'
      - '2222:22'
    depends_on:
      - mhedev-mysql

  panubo-ftp:
    image: panubo/vsftpd:latest
    hostname: panubo-ftp
    container_name: panubo-ftp
    environment:
      - SERVICE_NAME=panubo-ftp
      - FTP_USER=ftp
      - FTP_PASSWORD=ftp
      - FTP_CHOWN_ROOT=1
    volumes:
      - ./wordpress:/srv
    expose:
      - 21
    ports:
      - '21:21'
