version: "2"

services:
  # Contenedor de innstalación de PHP
  mhedev-php-7.4.25:
    build:
      context: ./docker
      dockerfile: Dockerfile-php-7.4.25
    image: mhedev/php:7.4.25
    container_name: mhedev-php-7.4.25
    hostname: mhedev-php-7.4.25
    environment:
      - SERVICE_NAME=mhedev-php-7.4.25
    command: php -v

  # Contenedor Wordpress
  mhedev-wordpress:
    build: ./wordpress
    image: mhedev/wordpress:5.8.1
    container_name: mhedev-wordpress
    hostname: mhedev-wordpress
    environment:
      - SERVICE_NAME=mhedev-wordpress
      - DATABASE_URL=mysql://mhedev:mhedev@mhedev-mysql:3306/mhedev
      - XDEBUG_SESSION=PHPSTORM
      - DOCKER_HOST=172.17.0.1 # Se puede determinar su valor ejecutando 'ifconfig' y verificando la ip de la interfaz 'docker0'.
    volumes:
      - ./wordpress:/var/www/html
    ports:
      - '8082:80'

  mhedev-ftp:
    container_name: mhedev-ftp
    hostname: mhedev-ftp
    image: bogem/ftp:latest
    environment:
      - SERVICE_NAME=mhedev-sftp
      - FTP_USER=ftp
      - FTP_PASS=mhedev
      - PASV_ADDRESS=mhedev-ftp
    volumes:
      - ./wordpress:/home/vsftpd
    expose:
      - 20
      - 21
      - 47400-47470
    ports:
      - '20:20'
      - '21:21'
      - '47400-47470:47400-47470'