version: "2"

services:
  wordpress-alpine:
    image: wordpress:php7.4-apache
    hostname: wordpress-alpine
    container_name: wordpress-alpine
    environment:
      - SERVICE_NAME=wordpress-alpine
      - WORDPRESS_DB_HOST=mhedev-mysql
      - WORDPRESS_DB_USER=mhedev
      - WORDPRESS_DB_PASSWORD=mhedev
      - WORDPRESS_DB_NAME=mhedev
    volumes:
      - ./wordpress:/var/www/html
    expose:
      - 22
    ports:
      - '8080:80'
      - '2222:22'
    depends_on:
      - mhedev-mysql

  mhedev-ftp:
    container_name: mhedev-ftp
    hostname: mhedev-ftp
    image: bogem/ftp:latest
    environment:
      - SERVICE_NAME=mhedev-sftp
      - FTP_USER=ftp
      - FTP_PASS=mhedev
      - PASV_ADDRESS=mhedev-ftp
    volumes:
      - ./wordpress:/home/vsftpd
    expose:
      - 20
      - 21
      - 47400-47470
    ports:
      - '20:20'
      - '21:21'
      - '47400-47470:47400-47470'